name: Auto Update PRs

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PRs
        uses: chinthakagodawita/autoupdate@0707656cd062a3b0cf8fa9b2cda1d1404d74437e # v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_msg: "chore: auto-update branch with main"
          pr_filter: "auto_merge"
          exclude_labels: "do-not-update"
          retry_interval: "2"
          retry_count: "3"
          update_limit: "5"
